import {
  BookOpen,
  Bot,
  Building2,
  Car,
  ClipboardCheck,
  Compass,
  FileText,
  Gauge,
  Globe,
  Home,
  Hotel,
  KeyRound,
  LayoutGrid,
  Library,
  LineChart,
  Link2,
  ListChecks,
  MapPin,
  MessageSquare,
  Palette,
  PenTool,
  RefreshCw,
  Scale,
  ScanSearch,
  Search,
  ShieldCheck,
  ShoppingCart,
  Smile,
  Sparkles,
  Swords,
  Tag,
  TrendingUp,
  Users,
  UtensilsCrossed,
  type LucideIcon,
} from 'lucide-react';
import type { NavIconKey } from '@/data/nav-menu';

export const NAV_ICONS: Record<NavIconKey, LucideIcon> = {
  search: Search,
  map: MapPin,
  sparkles: Sparkles,
  audit: ClipboardCheck,
  cart: ShoppingCart,
  trend: TrendingUp,
  link: Link2,
  pen: PenTool,
  globe: Globe,
  refresh: RefreshCw,
  gauge: Gauge,
  palette: Palette,
  hotel: Hotel,
  car: Car,
  compass: Compass,
  home: Home,
  utensils: UtensilsCrossed,
  building: Building2,
  scale: Scale,
  tooth: Smile,
  list: ListChecks,
  chart: LineChart,
  key: KeyRound,
  file: FileText,
  shield: ShieldCheck,
  swords: Swords,
  bot: Bot,
  message: MessageSquare,
  users: Users,
  book: BookOpen,
  library: Library,
  scan: ScanSearch,
  tag: Tag,
  grid: LayoutGrid,
};
